name: Nightly Build and Push

on:
  push:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  toollist:
    runs-on: ubuntu-latest
    outputs:
      tools: ${{ steps.tools.outputs.tools }}
    steps:
    - uses: actions/checkout@master
    - name: Tools
      id: tools
      run: |
        (
          echo -n "tools=";
          cat README.md | grep -- --tool-- | grep -v -- --no-test-- | tr '[]' ' ' | awk '{print $6}' | jq -R . | jq -c -s .;
        ) >> "$GITHUB_OUTPUT"
  toolcheck:
    needs: toollist
    strategy:
      fail-fast: false
      matrix:
        tool: ${{ fromJSON(needs.toollist.outputs.tools) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-buildx-action@master
    - name: Build Tool
      run: |
        docker build -t ctftools/${{ matrix.tool }} --build-arg PREINSTALL="${{ matrix.tool }}" .
